version: '3.0'
services:
  mpd:
    environment:
      - DOCKER_MPD_SERVER=192.168.2.150
      - DOCKER_MPD_PASSWORD=57obphZ95Av2aM
    build: .
    ports:
      - "6600:6600"
    volumes:
      - ./Music:/music
      - mpd_data:/mpd
volumes:
  mpd_data: {}
